### ISSUE TITLE
No search dots after update to version 1.1.2

### ISSUE THREAD

**Issue by jjmoonen** [NightwindDev/SearchDots#1]
Has been working fine until latest version, now when enabling, the dots disappear and no search option visible.

**Comment by jjmoonen** [comment]
Reinstalled the tweak, for now it's working again.

**Comment by jjmoonen** [comment]
Unfortunately it doesn't work for me, maybe it has something to do with Atria, don't know.

**Comment by NightwindDev** [comment]
I will upload a .deb with the fix in a couple hours. Sorry for the inconvenience.

**Comment by jjmoonen** [comment]
Okay. Thank you for your hard work. I appreciate it 😊

Jan Moonen
Via IPhone

Op 31 mei 2023 om 14:36 heeft Nightwind ***@***.***> het volgende geschreven:

﻿

I will upload a .deb with the fix in a couple hours. Sorry for the inconvenience.

**Comment by NightwindDev** [comment]
1.1.3 has been released on Chariz. It should fix the issue.

**Comment by jjmoonen** [comment]
Thank you, for now it’s working. 😊

Jan Moonen
Via IPhone

Op 31 mei 2023 om 18:01 heeft Nightwind ***@***.***> het volgende geschreven:

﻿

1.1.3 has been released on Chariz. It should fix the issue.

**Comment by NightwindDev** [comment]
Great! Glad to hear it.

**Comment by jjmoonen** [comment]
Thank you for your quick fix 🙏
